name: lint and test
on: [push]
jobs:
  ci:
    name: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "1.20"
      id: go
    - uses: golangci/golangci-lint-action@v3
    - run: go test ./...
